name: Documentation
on:
  push:
    branches:
      - master
      - main
permissions:
  contents: write
  pages: write
  id-token: write
jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Código
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Instalar Zensical
        run: |
          python -m pip install --upgrade pip
          pip install zensical

      - name: Compilar o Site (Build)
        run: zensical build --clean
